export const STORE_DATA_FROM_SERVER = 'STORE_DATA_FROM_SERVER';
export const SET_APP_MODE_TO_EDIT = 'SET_APP_MODE_TO_EDIT';
export const SET_APP_MODE_TO_ADD = 'SET_APP_MODE_TO_ADD';
export const ADD_ITEM = 'ADD_ITEM';

